Repository Stellarium/stellarium, pull requests merged in 2020-11, with the labels that each got.

#1304 solar system editor: improve docs + add confirmation dlg
  guide/app_ssystem_ini.tex
  guide/pictures/SolarSystemEditor-plugin-import2.png
  guide/plg_interfaces.tex
  plugins/SolarSystemEditor/src/SolarSystemEditor.cpp
  plugins/SolarSystemEditor/src/SolarSystemEditor.hpp
  plugins/SolarSystemEditor/src/gui/MpcImportWindow.cpp
  plugins/SolarSystemEditor/src/gui/MpcImportWindow.hpp
  plugins/SolarSystemEditor/src/gui/SolarSystemManagerWindow.cpp
  plugins/SolarSystemEditor/src/gui/SolarSystemManagerWindow.hpp
  plugins/SolarSystemEditor/src/gui/mpcImportWindow.ui
Labels: enhancement

#1361 Improve planets' halos size in relation to stars'
  src/core/StelSkyDrawer.cpp
  src/core/modules/Planet.cpp
Labels: enhancement

#1355 WUT: Algol-type filter
  src/core/StelUtils.cpp
  src/core/StelUtils.hpp
  src/core/modules/StarMgr.cpp
  src/core/modules/StarMgr.hpp
  src/core/modules/StarWrapper.cpp
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
Labels: enhancement

#1366 MSVC-static build note
  BUILDING.md
Labels: documentation

#1380 Updated Bengali Descriptions
  scenery3d/Sterngarten/description.bn.utf8
  scenery3d/Testscene/description.bn.utf8
  skycultures/almagest/description.bn.utf8
  skycultures/anutan/description.bn.utf8
  skycultures/arabic/description.bn.utf8
  skycultures/arabic_moon_stations/description.bn.utf8
  skycultures/armintxe/description.bn.utf8
  skycultures/aztec/description.bn.utf8
  skycultures/belarusian/description.bn.utf8
  skycultures/boorong/description.bn.utf8
  skycultures/chinese/description.bn.utf8
  skycultures/chinese_contemporary/description.bn.utf8
  skycultures/chinese_medieval/description.bn.utf8
  skycultures/dakota/description.bn.utf8
  skycultures/egyptian/description.bn.utf8
  skycultures/hawaiian_starlines/description.bn.utf8
  skycultures/indian/description.bn.utf8
  skycultures/inuit/description.bn.utf8
  skycultures/japanese_moon_stations/description.bn.utf8
  skycultures/kamilaroi/description.bn.utf8
  skycultures/korean/description.bn.utf8
  skycultures/lokono/description.bn.utf8
  skycultures/macedonian/description.bn.utf8
  skycultures/maori/description.bn.utf8
  skycultures/maya/description.bn.utf8
  skycultures/mongolian/description.bn.utf8
  skycultures/mulapin/description.bn.utf8
  skycultures/navajo/description.bn.utf8
  skycultures/norse/description.bn.utf8
  skycultures/northern_andes/description.bn.utf8
  skycultures/ojibwe/description.bn.utf8
  skycultures/romanian/description.bn.utf8
  skycultures/sami/description.bn.utf8
  skycultures/sardinian/description.bn.utf8
  skycultures/seleucid/description.bn.utf8
  skycultures/siberian/description.bn.utf8
  skycultures/tongan/description.bn.utf8
  skycultures/tukano/description.bn.utf8
  skycultures/tupi/description.bn.utf8
  skycultures/vanuatu_netwar/description.bn.utf8
  skycultures/western/description.bn.utf8
  skycultures/western_SnT/description.bn.utf8
  skycultures/western_hlad/description.bn.utf8
  skycultures/western_rey/description.bn.utf8
  util/ISL/BengaliCM.isl
Labels: translations
