Repository Stellarium/stellarium, pull requests merged in 2020-08, with the labels that each got.

#1198 Add Full Sensor Grid to Ocular plugin
  plugins/Oculars/src/Oculars.cpp
  plugins/Oculars/src/Oculars.hpp
  plugins/Oculars/src/gui/OcularDialog.cpp
  plugins/Oculars/src/gui/ocularDialog.ui
Labels: enhancement

#1168 added recent search
  data/gui/normalStyle.css
  guide/ch_interface.tex
  guide/pictures/search_dialog_option.png
  guide/pictures/search_dialog_recent_result.png
  src/gui/SearchDialog.cpp
  src/gui/SearchDialog.hpp
  src/gui/searchDialogGui.ui
Labels: feature request

#1220 Remove QSignalMapper
  plugins/TelescopeControl/src/TelescopeControl.cpp
  src/core/StelActionMgr.cpp
  src/core/StelActionMgr.hpp
  src/core/StelModule.cpp
  src/core/StelModule.hpp
  src/scripting/StelScriptMgr.cpp
Labels: fix committed, medium importance
