Repository Stellarium/stellarium, pull requests merged in 2020-12, with the labels that each got.

#1388 Add a config option to use multisampling for rendering "Planet"s
  guide/app_config_ini.tex
  src/StelMainView.cpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
Labels: enhancement

#1401 Refine docs on the multisampling option
  guide/app_config_ini.tex
Labels: documentation

#1390 Added build AppImage packages
  .github/workflows/appimage.yml
  util/appimage/build-appimage.sh
  util/appimage/stellarium-appimage-aarch64.yml
  util/appimage/stellarium-appimage-armhf.yml
  util/appimage/stellarium-appimage-x86_64.yml
Labels: infrastructure

#1383 Added JPL DE430 for unit tests
  .github/workflows/ci.yml
Labels: infrastructure

#1411 guide: remove duplicate line
  guide/ch_astronomical_phenomena.tex
Labels: documentation

#1424 some pointers for newcomers
  BUILDING.md
  README.md
Labels: documentation

#1440 Fix Mensa and Microscopium in S&T skyculture
  skycultures/western_SnT/constellationship.fab
  skycultures/western_SnT/generate_constellationship.py
Labels: data

#1444 Update building instructions for Windows
  BUILDING.md
Labels: documentation

#1451 Fix styles of QMessageBox and QColorDialog
  data/gui/normalStyle.css
  plugins/MeteorShowers/src/gui/MSConfigDialog.cpp
  plugins/Satellites/src/gui/SatellitesDialog.cpp
  plugins/SolarSystemEditor/src/gui/ManualImportWindow.cpp
  src/gui/AddRemoveLandscapesDialog.cpp
  src/gui/ScriptConsole.cpp
  src/gui/StelDialog.cpp
Labels: enhancement
