Repository Stellarium/stellarium, pull requests merged in 2021-11, with the labels that each got.

#2006 Allow compilation by disabling cmake flag WITH_QTWEBENGINE
  BUILDING.md
  CMakeLists.txt
  guide/plg_catalogs.tex
  plugins/OnlineQueries/src/CMakeLists.txt
  plugins/OnlineQueries/src/gui/OnlineQueriesDialog.cpp
  plugins/OnlineQueries/src/gui/StelWebEngineView.cpp
  plugins/OnlineQueries/src/gui/StelWebEngineView.hpp
Labels: enhancement, confirmed, critical importance, qt

#2005 Refactoring the support of the on-screen stars names
  guide/app_config_ini.tex
  guide/app_star_catalogue.tex
  guide/ch_interface.tex
  guide/pictures/view_dialog_sky_tab.png
  src/core/modules/Star.cpp
  src/core/modules/StarMgr.cpp
  src/core/modules/StarMgr.hpp
  src/core/modules/StarWrapper.cpp
  src/gui/ConfigurationDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/viewDialog.ui
  stars/default/extra_name.fab
  stars/default/name.fab
Labels: enhancement

#2027 Orbit epoch
  guide/app_ssystem_ini.tex
  guide/ch_astronomical_phenomena.tex
  plugins/SolarSystemEditor/src/SolarSystemEditor.cpp
  src/core/modules/MinorPlanet.cpp
  src/core/modules/Orbit.cpp
  src/core/modules/Orbit.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/core/modules/SolarSystem.cpp
  src/gui/AstroCalcDialog.cpp
Labels: enhancement

#2037 Add Solar and Lunar info to InfoString (Fix #1455)
  src/core/StelObject.cpp
  src/core/StelObject.hpp
  src/core/modules/Asterism.cpp
  src/core/modules/Constellation.cpp
  src/core/modules/CustomObject.cpp
  src/core/modules/Nebula.cpp
  src/core/modules/Planet.cpp
  src/core/modules/StarWrapper.cpp
  src/gui/ConfigurationDialog.cpp
  src/gui/configurationDialog.ui
Labels: enhancement, low importance

#2038 InfoString fixes
  guide/app_config_ini.tex
  src/core/StelObject.cpp
  src/core/StelObject.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/ConfigurationDialog.hpp
  src/gui/SkyGui.cpp
  src/gui/configurationDialog.ui
Labels: enhancement, low importance

#2049 Additional cmake fixes over #2006
  CMakeLists.txt
  plugins/OnlineQueries/CMakeLists.txt
  plugins/OnlineQueries/src/CMakeLists.txt
  plugins/OnlineQueries/src/gui/OnlineQueriesDialog.cpp
  plugins/OnlineQueries/src/gui/onlineQueriesDialog.ui
Labels: help wanted, infrastructure, qt
