Repository Stellarium/stellarium, pull requests merged in 2021-09, with the labels that each got.

#1862 Introducing new western sky culture sternenkarten.com
  po/stellarium-skycultures/POTFILES.in
  skycultures/CMakeLists.txt
  skycultures/western_sternenkarten/CMakeLists.txt
  skycultures/western_sternenkarten/constellation_names.eng.fab
  skycultures/western_sternenkarten/constellationship.fab
  skycultures/western_sternenkarten/description.de.utf8
  skycultures/western_sternenkarten/description.en.utf8
  skycultures/western_sternenkarten/info.ini
  skycultures/western_sternenkarten/reference.fab
  skycultures/western_sternenkarten/star_names.fab
  src/translations.h
Labels: enhancement, data

#1885 Greatest Digression
  guide/ch_astronomical_concepts.tex
  guide/plg_archaeolines.tex
  src/core/StelObject.cpp
Labels: feature request

#1889 Typofixes and better translations for Lunar regions
  data/regions-geoscheme.tab
  src/translations_regions.h
Labels: medium importance

#1852 Planet RTS
  guide/app_config_ini.tex
  guide/ch_astronomical_phenomena.tex
  guide/ch_interface.tex
  guide/pictures/view_dialog_sky_tab.png
  guide/plg_atTheTelescope.tex
  plugins/MeteorShowers/src/gui/MSSearchDialog.cpp
  plugins/Observability/src/Observability.cpp
  plugins/Observability/src/gui/ObservabilityDialog.cpp
  src/core/StelCore.hpp
  src/core/StelObject.cpp
  src/core/StelObject.hpp
  src/core/StelObjectMgr.cpp
  src/core/StelObjectMgr.hpp
  src/core/StelUtils.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/viewDialog.ui
Labels: enhancement, medium importance

#1880 Exclude outdated solar system objects
  src/core/modules/Orbit.cpp
  src/core/modules/Orbit.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
Labels: bug, enhancement

#1910 Astrocalc: findRightAscension replacement
  src/gui/AstroCalcDialog.cpp
Labels: medium importance

#1898 typos
  skycultures/greek_farnese/description.en.utf8
  skycultures/greek_leidenAratea/description.en.utf8
Labels: description
