Repository Stellarium/stellarium, pull requests merged in 2022-01, with the labels that each got.

#2085 GZ atmosphere tweaks
  data/shaders/atmosphere.vert
  data/shaders/xyYToRGB.glsl
  guide/ch_skylight.tex
  guide/guide.bib
  guide/guide.tex
  guide/structure.tex
  src/CMakeLists.txt
  src/core/StelCore.cpp
  src/core/StelSkyDrawer.cpp
  src/core/StelSkyDrawer.hpp
  src/core/StelToneReproducer.cpp
  src/core/StelToneReproducer.hpp
  src/core/modules/Atmosphere.cpp
  src/core/modules/Atmosphere.hpp
  src/core/modules/LandscapeMgr.cpp
  src/core/modules/LandscapeMgr.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Skylight.cpp
  src/core/modules/Skylight.hpp
  src/core/modules/SolarSystem.cpp
  src/gui/AtmosphereDialog.cpp
  src/gui/AtmosphereDialog.hpp
  src/gui/SkylightDialog.cpp
  src/gui/SkylightDialog.hpp
  src/gui/TonemappingDialog.cpp
  src/gui/TonemappingDialog.hpp
  src/gui/ViewDialog.cpp
  src/gui/ViewDialog.hpp
  src/gui/atmosphereDialog.ui
  src/gui/skylightDialog.ui
  src/gui/tonemappingDialog.ui
  src/gui/viewDialog.ui
  src/scripting/StelMainScriptAPI.cpp
  src/scripting/StelMainScriptAPI.hpp
Labels: enhancement

#2132 Allow moving StelDialogSeparate to a separate screen
  src/gui/Dialog.cpp
  src/gui/Dialog.hpp
  src/gui/StelDialogSeparate.cpp
Labels: enhancement

#2158 Fix nomenclature longitudes
  guide/app_nomenclature.tex
  guide/structure.tex
  src/core/StelObject.cpp
  src/core/StelPainter.cpp
  src/core/StelPainter.hpp
  src/core/StelUtils.cpp
  src/core/StelUtils.hpp
  src/core/modules/NomenclatureItem.cpp
  src/core/modules/NomenclatureItem.hpp
  src/core/modules/NomenclatureMgr.cpp
  src/core/modules/NomenclatureMgr.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/core/modules/SpecialMarkersMgr.cpp
  src/tests/testConversions.cpp
  src/tests/testConversions.hpp
  textures/tethys.png
Labels: enhancement, medium importance, documentation

#2180 Refactor: getAngularSize->getAngularRadius
  plugins/Exoplanets/src/Exoplanet.cpp
  plugins/Exoplanets/src/Exoplanet.hpp
  plugins/MeteorShowers/src/MeteorShower.cpp
  plugins/MeteorShowers/src/MeteorShower.hpp
  plugins/MeteorShowers/src/MeteorShowers.cpp
  plugins/NavStars/src/NavStars.cpp
  plugins/Novae/src/Nova.cpp
  plugins/Novae/src/Nova.hpp
  plugins/Pulsars/src/Pulsar.cpp
  plugins/Pulsars/src/Pulsar.hpp
  plugins/Quasars/src/Quasar.cpp
  plugins/Quasars/src/Quasar.hpp
  plugins/Satellites/src/Satellite.cpp
  plugins/Satellites/src/Satellite.hpp
  plugins/Satellites/src/Satellites.cpp
  plugins/Supernovae/src/Supernova.cpp
  plugins/Supernovae/src/Supernova.hpp
  plugins/TelescopeControl/src/TelescopeClient.hpp
  src/core/StelObject.cpp
  src/core/StelObject.hpp
  src/core/modules/Asterism.hpp
  src/core/modules/Comet.cpp
  src/core/modules/Constellation.hpp
  src/core/modules/CustomObject.cpp
  src/core/modules/CustomObject.hpp
  src/core/modules/LabelMgr.cpp
  src/core/modules/Nebula.cpp
  src/core/modules/Nebula.hpp
  src/core/modules/NebulaMgr.cpp
  src/core/modules/NomenclatureItem.cpp
  src/core/modules/NomenclatureItem.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/core/modules/SolarSystem.cpp
  src/core/modules/StarWrapper.hpp
  src/gui/AstroCalcDialog.cpp
Labels: low importance, documentation

#2187 Remove default grs
  guide/app_config_ini.tex
  guide/ch_interface.tex
  guide/pictures/view_dialog_sso_tab.png
  src/core/modules/RotationElements.cpp
  src/core/modules/RotationElements.hpp
  src/core/modules/SolarSystem.cpp
  src/core/modules/SolarSystem.hpp
  src/gui/GreatRedSpotDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/viewDialog.ui
Labels: enhancement

#2199 Compactification of the GUI
  guide/ch_interface.tex
  guide/ch_skylight.tex
  guide/pictures/uibtEdit.png
  guide/pictures/uibtProcess.png
  guide/pictures/uibtSettings.png
  src/gui/ViewDialog.cpp
  src/gui/atmosphereDialog.ui
  src/gui/greatRedSpotDialog.ui
  src/gui/viewDialog.ui
Labels: enhancement

#2190 Add Lunar Eclipses to Astronomical calculations
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: wishlist

#2218 Add Solar Eclipses to Astronomical calculations
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: feature request

#2220 Martian Poles
  data/shaders/planet.frag
  guide/app_acknowledgements.tex
  guide/guide.bib
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
Labels: feature request, low importance

#2214 Add Revised Julian Calendar
  guide/plg_calendars.tex
  plugins/Calendars/src/CMakeLists.txt
  plugins/Calendars/src/Calendar.cpp
  plugins/Calendars/src/Calendar.hpp
  plugins/Calendars/src/Calendars.cpp
  plugins/Calendars/src/Calendars.hpp
  plugins/Calendars/src/GregorianCalendar.hpp
  plugins/Calendars/src/JulianCalendar.hpp
  plugins/Calendars/src/RevisedJulianCalendar.cpp
  plugins/Calendars/src/RevisedJulianCalendar.hpp
  plugins/Calendars/src/gui/CalendarsDialog.cpp
  plugins/Calendars/src/gui/calendarsDialog.ui
  plugins/Calendars/src/test/testCalendars.cpp
Labels: feature request
