Repository Stellarium/stellarium, pull requests merged in 2022-05, with the labels that each got.

#2416 Meteor Showers plugin Improvements
  guide/guide.bib
  guide/plg_catalogs.tex
  plugins/MeteorShowers/CMakeLists.txt
  plugins/MeteorShowers/resources/MeteorShower.qrc
  plugins/MeteorShowers/resources/MeteorShowers.json
  plugins/MeteorShowers/src/MeteorShower.cpp
  plugins/MeteorShowers/src/MeteorShower.hpp
  plugins/MeteorShowers/src/MeteorShowers.cpp
  plugins/MeteorShowers/src/MeteorShowers.hpp
  plugins/MeteorShowers/src/MeteorShowersMgr.cpp
  plugins/MeteorShowers/src/MeteorShowersMgr.hpp
  plugins/MeteorShowers/src/gui/MSConfigDialog.cpp
  plugins/MeteorShowers/src/gui/MSSearchDialog.cpp
  plugins/MeteorShowers/src/gui/MSSearchDialog.hpp
  plugins/MeteorShowers/src/gui/MSSearchDialog.ui
  plugins/MeteorShowers/src/translations.h
Labels: enhancement

#2451 Added visualisation Earth umbra and penumbra for satellites
  guide/pictures/satellites_plugin_configuration.jpg
  guide/pictures/satellites_plugin_configuration.png
  guide/plg_catalogs.tex
  plugins/Satellites/src/Satellites.cpp
  plugins/Satellites/src/Satellites.hpp
  plugins/Satellites/src/gui/SatellitesDialog.cpp
  plugins/Satellites/src/gui/SatellitesDialog.hpp
  plugins/Satellites/src/gui/satellitesDialog.ui
Labels: feature request

#2457 Added custom filter for satellites
  guide/pictures/satellites_plugin_filters.jpg
  guide/pictures/satellites_plugin_satellites.jpg
  guide/pictures/satellites_plugin_satellites.png
  guide/plg_catalogs.tex
  plugins/Satellites/src/CMakeLists.txt
  plugins/Satellites/src/Satellite.cpp
  plugins/Satellites/src/Satellite.hpp
  plugins/Satellites/src/Satellites.cpp
  plugins/Satellites/src/Satellites.hpp
  plugins/Satellites/src/gui/SatellitesDialog.cpp
  plugins/Satellites/src/gui/SatellitesDialog.hpp
  plugins/Satellites/src/gui/SatellitesFilterDialog.cpp
  plugins/Satellites/src/gui/SatellitesFilterDialog.hpp
  plugins/Satellites/src/gui/satellitesDialog.ui
  plugins/Satellites/src/gui/satellitesFilterDialog.ui
  po/stellarium/POTFILES.in
Labels: feature request

#2463 add new names to DSO
  nebulae/default/names.dat
Labels: data

#2465 Fix slow down of time when the Moon is selected
  src/core/modules/Planet.cpp
Labels: enhancement, medium importance
