Repository Stellarium/stellarium, pull requests merged in 2022-04, with the labels that each got.

#2399 Add fixed equatorial grid/line
  guide/app_config_ini.tex
  guide/ch_astronomical_concepts.tex
  src/core/StelCore.cpp
  src/core/StelCore.hpp
  src/core/modules/GridLinesMgr.cpp
  src/core/modules/GridLinesMgr.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/viewDialog.ui
Labels: feature request

#2405 Added support directional elongation
  src/core/StelUtils.hpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/configurationDialog.ui
  src/scripting/StelMainScriptAPI.hpp
Labels: enhancement

#2412 add DSO-names and some Barnard outlines
  nebulae/default/names.dat
  nebulae/default/outlines.dat
Labels: data

#2421 Tiny Milky Way texture improvement
  textures/milkyway.png
Labels: data

#2423 Fix MacOS build on ARM64 (Apple Silicon)
  BUILDING.md
  CMakeLists.txt
Labels: infrastructure
