Repository Stellarium/stellarium, pull requests merged in 2022-10, with the labels that each got.

#2720 New rules for packaging
  .appveyor.yml
  .github/workflows/appimage.yml
  CMakeLists.txt
  cmake/stellarium-patch.iss.cmake
  src/CMakeLists.txt
  util/appimage/build-appimage.sh
Labels: infrastructure

#2723 Optional support XLSX files
  CMakeLists.txt
  plugins/Satellites/src/CMakeLists.txt
  plugins/Satellites/src/gui/SatellitesDialog.cpp
  src/CMakeLists.txt
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
Labels: infrastructure

#2742 Replace world map with a higher-resolution version
  CREDITS.md
  data/gui/guiRes.qrc
  data/gui/miscWorldMap.jpg
  data/gui/miscWorldMap.png
  src/gui/LocationDialog.cpp
  src/gui/MapWidget.cpp
Labels: enhancement

#2773 Add donation link to AppStream Metadata
  data/org.stellarium.Stellarium.appdata.xml
Labels: infrastructure

#2772 GUI: allow user CSS
  data/CMakeLists.txt
  data/gui/normalStyle.css
  guide/ch_advanced_use.tex
  plugins/MeteorShowers/src/MeteorShowersMgr.cpp
  plugins/MeteorShowers/src/MeteorShowersMgr.hpp
  plugins/MeteorShowers/src/gui/MSConfigDialog.cpp
  plugins/MeteorShowers/src/gui/MSConfigDialog.hpp
  plugins/MeteorShowers/src/gui/MSConfigDialog.ui
  plugins/Satellites/src/gui/SatellitesDialog.cpp
  src/CLIProcessor.cpp
  src/CMakeLists.txt
  src/StelMainView.hpp
  src/core/StelApp.cpp
  src/core/StelApp.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/HelpDialog.cpp
  src/gui/HelpDialog.hpp
  src/gui/LocationDialog.cpp
  src/gui/LocationDialog.hpp
  src/gui/ScriptConsole.cpp
  src/gui/ScriptConsole.hpp
  src/gui/SearchDialog.cpp
  src/gui/ShortcutsDialog.cpp
  src/gui/StelDialog.cpp
  src/gui/StelDialog.hpp
  src/gui/StelDialogSeparate.cpp
  src/gui/StelDialogSeparate.hpp
  src/gui/StelGui.cpp
  src/gui/StelGui.hpp
  src/gui/StelScriptSyntaxHighlighter.cpp
  src/gui/StelStyle.hpp
  src/gui/ViewDialog.cpp
  src/gui/ViewDialog.hpp
  src/scripting/StelMainScriptAPI.cpp
  src/scripting/StelMainScriptAPI.hpp
Labels: feature, importance: low

#2761 Simplify dev setup
  .github/workflows/appimage.yml
  .github/workflows/ci-beta.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality.yml
  .github/workflows/codeql-analysis.yml
  BUILDING.md
  CMakeLists.txt
Labels: infrastructure
