Repository Stellarium/stellarium, pull requests merged in 2022-08, with the labels that each got.

#2549 Enhancement for the AstroCalc/Positions tool
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: enhancement

#2573 Add contact times for lunar eclipses in AstroCal
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: enhancement

#2586 Enable video playing in Qt6 builds
  scripts/tests/media/stellarium.mp4
  scripts/tests/videotest_popout.ssc
  src/core/StelAudioMgr.cpp
  src/core/StelVideoMgr.cpp
  src/core/StelVideoMgr.hpp
  src/scripting/StelMainScriptAPI.hpp
Labels: importance: medium, qt

#2545 Added support public version of Stellarium
  CMakeLists.txt
  cmake/Doxyfile.cmake
  cmake/default_cfg.ini.cmake
  cmake/version.tex.cmake
  src/StelMainView.cpp
  src/StelSplashScreen.cpp
  src/core/StelModuleMgr.cpp
  src/core/StelUtils.cpp
  src/core/StelUtils.hpp
  src/gui/HelpDialog.cpp
  src/main.cpp
Labels: infrastructure

#2592 Fix map update. (Fix #1302)
  plugins/RemoteControl/src/LocationService.cpp
  plugins/RemoteControl/webroot/js/api/location.js
  src/gui/LocationDialog.cpp
Labels: bug, importance: low
