Repository Stellarium/stellarium, pull requests merged in 2022-09, with the labels that each got.

#2604 Add support for ShowMySky atmosphere model
  .appveyor.yml
  .github/workflows/ci-beta.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality.yml
  .github/workflows/codeql-analysis.yml
  .lgtm.yml
  CMakeLists.txt
  data/mainRes.qrc
  data/shaders/preethamAtmosphere.vert
  src/CMakeLists.txt
  src/core/modules/Atmosphere.hpp
  src/core/modules/AtmospherePreetham.cpp
  src/core/modules/AtmospherePreetham.hpp
  src/core/modules/AtmosphereShowMySky.cpp
  src/core/modules/AtmosphereShowMySky.hpp
  src/core/modules/LandscapeMgr.cpp
  src/core/modules/LandscapeMgr.hpp
  src/gui/AtmosphereDialog.cpp
  src/gui/AtmosphereDialog.hpp
  src/gui/atmosphereDialog.ui
  src/gui/viewDialog.ui
Labels: enhancement

#2627 Adding a new Stellarium Sky Culture: Samoan
  po/stellarium-skycultures/POTFILES.in
  skycultures/CMakeLists.txt
  skycultures/greek_almagest/description.bn.utf8
  skycultures/greek_almagest/description.de.utf8
  skycultures/greek_almagest/description.en.utf8
  skycultures/greek_almagest/description.es.utf8
  skycultures/greek_almagest/description.fr.utf8
  skycultures/greek_almagest/description.hr.utf8
  skycultures/greek_almagest/description.ja.utf8
  skycultures/greek_almagest/description.nl.utf8
  skycultures/greek_almagest/description.ru.utf8
  skycultures/greek_almagest/description.sk.utf8
  skycultures/samoan/CMakeLists.txt
  skycultures/samoan/constellation_names.eng.fab
  skycultures/samoan/constellationship.fab
  skycultures/samoan/description.en.utf8
  skycultures/samoan/dso_names.fab
  skycultures/samoan/info.ini
  skycultures/samoan/planet_names.fab
  skycultures/samoan/star_names.fab
  util/skycultures/po4a.config
Labels: data

#2637 Set default atmosphere model path in the Atmosphere Details dialog
  src/core/modules/LandscapeMgr.cpp
  src/core/modules/LandscapeMgr.hpp
  src/gui/AtmosphereDialog.cpp
Labels: enhancement

#2639 Add more maintainer docs
  BUILDING.md
  MAINTAINER_BUSINESS.md
  src/external/CMakeLists.txt
Labels: documentation, infrastructure

#2628 Added config viewer
  src/gui/HelpDialog.cpp
  src/gui/HelpDialog.hpp
  src/gui/helpDialogGui.ui
Labels: enhancement

#2644 Enable dithering by default
  src/core/StelPainter.cpp
Labels: enhancement

#2636 Add some documentation for ShowMySky in the User Guide
  guide/ch_interface.tex
  guide/pictures/uibtFolder.png
Labels: documentation

#2646 Add financial contributors
  src/gui/HelpDialog.cpp
Labels: enhancement

#2648 Milky Way and Zodiacal Light rebalance
  src/core/modules/AtmospherePreetham.cpp
  src/core/modules/AtmosphereShowMySky.cpp
  src/core/modules/MilkyWay.cpp
  src/core/modules/ZodiacalLight.cpp
Labels: enhancement, importance: medium

#2620 GPS location managed by Windows
  guide/ch_advanced_use.tex
  src/core/StelLocationMgr.cpp
  src/core/StelLocationMgr.hpp
Labels: enhancement

#2652 Add contact times of global solar eclipse in AstroCal
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: enhancement

#2659 Upvector refix
  scripts/tests/test-upvector.ssc
  src/core/StelMovementMgr.cpp
  src/core/StelMovementMgr.hpp
  src/scripting/StelMainScriptAPI.cpp
Labels: enhancement

#2660 Add support for up to 500% scaling of dialog close button
  data/gui/normalStyle.css
  data/gui/uieCloseButton-hover.png
  data/gui/uieCloseButton.png
  plugins/AngleMeasure/src/gui/angleMeasureDialog.ui
  plugins/ArchaeoLines/src/gui/archaeoLinesDialog.ui
  plugins/ArchaeoLines/src/gui/archaeoLinesDialogLocations.ui
  plugins/Calendars/src/gui/calendarsDialog.ui
  plugins/EquationOfTime/src/gui/equationOfTimeWindow.ui
  plugins/Exoplanets/src/gui/exoplanetsDialog.ui
  plugins/MeteorShowers/src/gui/MSConfigDialog.ui
  plugins/MeteorShowers/src/gui/MSSearchDialog.ui
  plugins/NavStars/src/gui/navStarsWindow.ui
  plugins/Novae/src/gui/novaeDialog.ui
  plugins/Observability/src/gui/ObservabilityDialog.ui
  plugins/Oculars/src/gui/ocularDialog.ui
  plugins/OnlineQueries/src/gui/onlineQueriesDialog.ui
  plugins/PointerCoordinates/src/gui/pointerCoordinatesWindow.ui
  plugins/Pulsars/src/gui/pulsarsDialog.ui
  plugins/Quasars/src/gui/quasarsDialog.ui
  plugins/RemoteControl/src/gui/remoteControlDialog.ui
  plugins/RemoteSync/src/gui/remoteSyncDialog.ui
  plugins/Satellites/src/gui/satellitesCommDialog.ui
  plugins/Satellites/src/gui/satellitesDialog.ui
  plugins/Satellites/src/gui/satellitesFilterDialog.ui
  plugins/Satellites/src/gui/satellitesImportDialog.ui
  plugins/Scenery3d/src/gui/scenery3dDialog.ui
  plugins/Scenery3d/src/gui/storedViewDialog.ui
  plugins/SolarSystemEditor/src/gui/manualImportWindow.ui
  plugins/SolarSystemEditor/src/gui/mpcImportWindow.ui
  plugins/SolarSystemEditor/src/gui/solarSystemManagerWindow.ui
  plugins/Supernovae/src/gui/supernovaeDialog.ui
  plugins/TelescopeControl/src/gui/slewDialog.ui
  plugins/TelescopeControl/src/gui/storedPointsDialog.ui
  plugins/TelescopeControl/src/gui/telescopeConfigurationDialog.ui
  plugins/TelescopeControl/src/gui/telescopeDialog.ui
  src/CMakeLists.txt
  src/gui/StelCloseButton.cpp
  src/gui/StelCloseButton.hpp
  src/gui/addRemoveLandscapesDialog.ui
  src/gui/astroCalcCustomStepsDialog.ui
  src/gui/astroCalcDialog.ui
  src/gui/astroCalcExtraEphemerisDialog.ui
  src/gui/atmosphereDialog.ui
  src/gui/configurationDialog.ui
  src/gui/configureScreenshotsDialog.ui
  src/gui/customDeltaTEquationDialog.ui
  src/gui/dateTimeDialogGui.ui
  src/gui/dsoColorsDialog.ui
  src/gui/greatRedSpotDialog.ui
  src/gui/helpDialogGui.ui
  src/gui/locationDialogGui.ui
  src/gui/obsListCreateEditDialog.ui
  src/gui/obsListDialog.ui
  src/gui/orbitColorsDialog.ui
  src/gui/scriptConsole.ui
  src/gui/searchDialogGui.ui
  src/gui/shortcutsDialog.ui
  src/gui/skylightDialog.ui
  src/gui/tonemappingDialog.ui
  src/gui/viewDialog.ui
Labels: enhancement

#2668 Paint version on the fly on the splash screen instead of rasterizing it into a pixmap
  src/StelSplashScreen.cpp
  src/StelSplashScreen.hpp
Labels: enhancement

#2673 Make it easy to disable search for Qt6
  CMakeLists.txt
Labels: infrastructure

#2677 Add capability to create KML map of solar eclipses in AstroCalc
  guide/ch_interface.tex
  guide/pictures/eclipsemap.pdf
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: feature

#2553 Observing lists fix
  po/stellarium/fr.po
  src/gui/ObsListCreateEditDialog.cpp
  src/gui/ObsListCreateEditDialog.hpp
  src/gui/ObsListDialog.cpp
  src/gui/ObsListDialog.hpp
  src/gui/ObservingListCommon.hpp
  src/gui/obsListCreateEditDialog.ui
  src/gui/obsListDialog.ui
  stellarium.kdev4
Labels: bug, enhancement

#2676 Enjoy ShowMySky on HDPI GPU with limited graphics performance.
  guide/ch_skylight.tex
  src/core/modules/AtmosphereShowMySky.cpp
  src/core/modules/AtmosphereShowMySky.hpp
Labels: enhancement

#2702 Fix missing segments in solar eclipse kml
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
Labels: enhancement

#2694 Fix/observing lists gz
  guide/ch_tour.tex
  src/CMakeLists.txt
  src/core/StelLocationMgr.cpp
  src/gui/ObsListCreateEditDialog.cpp
  src/gui/ObsListCreateEditDialog.hpp
  src/gui/ObsListDialog.cpp
  src/gui/ObsListDialog.hpp
  src/gui/ObservingListCommon.hpp
  src/gui/obsListCreateEditDialog.ui
  src/gui/obsListDialog.ui
Labels: enhancement

#2703 Increase size of spinbox and scrollbar arrows by 5× to improve the look on high-DPI monitors
  data/gui/guiRes.qrc
  data/gui/normalStyle.css
  data/gui/uieScrolldown.png
  data/gui/uieScrollleft.png
  data/gui/uieScrollright.png
  data/gui/uieScrollup.png
  data/gui/uieSpindown-pressed.png
  data/gui/uieSpindown.png
  data/gui/uieSpinleft-pressed.png
  data/gui/uieSpinleft.png
  data/gui/uieSpinright-pressed.png
  data/gui/uieSpinright.png
  data/gui/uieSpinup-pressed.png
  data/gui/uieSpinup.png
Labels: enhancement
