Repository Stellarium/stellarium, pull requests merged in 2023-02, with the labels that each got.

#3057 Grids: accurate ecliptic calendar marks
  guide/ch_astronomical_concepts.tex
  guide/ch_interface.tex
  guide/pictures/view_dialog_markings_tab.jpg
  guide/pictures/view_dialog_markings_tab.png
  src/core/StelCore.hpp
  src/core/StelMovementMgr.cpp
  src/core/StelUtils.cpp
  src/core/StelUtils.hpp
  src/core/modules/GridLinesMgr.cpp
  src/core/modules/GridLinesMgr.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/ConfigurationDialog.cpp
  src/gui/DateTimeDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/viewDialog.ui
  src/tests/testDates.cpp
  src/tests/testDates.hpp
Labels: feature

#3066 Ignore cmake-build-debug directory
  .gitignore
Labels: infrastructure

#3073 Make fps intent settings available in the GUI
  guide/ch_interface.tex
  guide/pictures/config_dialog_tools_tab.png
  guide/plg_atTheTelescope.tex
  src/StelMainView.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/configurationDialog.ui
Labels: enhancement
