Repository Stellarium/stellarium, pull requests merged in 2023-11, with the labels that each got.

#3496 FIx formatting issues so that copy and paste works
  BUILDING.md
Labels: documentation

#3505 Allow line loops on Cylindrical projection.
  plugins/Satellites/src/Satellites.cpp
  src/core/StelVertexArray.cpp
  src/core/modules/GridLinesMgr.cpp
Labels: importance: medium

#3434 New Skyculture: Tibetan Lunar Mansions
  po/stellarium-skycultures/POTFILES.in
  skycultures/CMakeLists.txt
  skycultures/tibetan/CMakeLists.txt
  skycultures/tibetan/MenTseeKhang_Emblem.jpg
  skycultures/tibetan/StagPhuDisk.jpg
  skycultures/tibetan/StagPhu_01_Ari.jpg
  skycultures/tibetan/StagPhu_02_Tau.jpg
  skycultures/tibetan/StagPhu_03_Gem.jpg
  skycultures/tibetan/StagPhu_04_Cnc_Frog.jpg
  skycultures/tibetan/StagPhu_05_Leo.jpg
  skycultures/tibetan/StagPhu_06_Vir.jpg
  skycultures/tibetan/StagPhu_07_Lib.jpg
  skycultures/tibetan/StagPhu_08_Sco.jpg
  skycultures/tibetan/StagPhu_09_Sgr.jpg
  skycultures/tibetan/StagPhu_10_Cap.jpg
  skycultures/tibetan/StagPhu_11_Aqr.jpg
  skycultures/tibetan/StagPhu_12_Psc.jpg
  skycultures/tibetan/aquarius.png
  skycultures/tibetan/aries.png
  skycultures/tibetan/asterism_lines.fab
  skycultures/tibetan/asterism_names.eng.fab
  skycultures/tibetan/cancer.png
  skycultures/tibetan/capricornus.png
  skycultures/tibetan/constellation_names.eng.fab
  skycultures/tibetan/constellationsart.fab
  skycultures/tibetan/constellationship.fab
  skycultures/tibetan/description.en.utf8
  skycultures/tibetan/gemini.png
  skycultures/tibetan/info.ini
  skycultures/tibetan/leo.png
  skycultures/tibetan/libra.png
  skycultures/tibetan/pisces.png
  skycultures/tibetan/reference.fab
  skycultures/tibetan/sagittarius.png
  skycultures/tibetan/scorpius.png
  skycultures/tibetan/star_names.fab
  skycultures/tibetan/taurus.png
  skycultures/tibetan/virgo.png
  util/skycultures/po4a.config
Labels: feature
