Repository Stellarium/stellarium, pull requests merged in 2023-09, with the labels that each got.

#3389 Updated comet discovery circumstances
  plugins/SolarSystemEditor/resources/comet_discovery.fab
Labels: data

#3207 Fix observing list import/export
  guide/ch_tour.tex
  src/gui/ObsListDialog.cpp
  src/gui/ObsListDialog.hpp
  src/gui/obsListDialog.ui
Labels: bug, enhancement, importance: medium, state: implemented

#3433 Remote control command to change window size
  plugins/RemoteControl/doc/remoteControlApi.doxygen
  plugins/RemoteControl/src/APIController.hpp
  plugins/RemoteControl/src/AbstractAPIService.hpp
  plugins/RemoteControl/src/LocationSearchService.hpp
  plugins/RemoteControl/src/LocationService.hpp
  plugins/RemoteControl/src/MainService.cpp
  plugins/RemoteControl/src/MainService.hpp
  plugins/RemoteControl/src/ObjectService.hpp
  plugins/RemoteControl/src/RemoteControl.cpp
  plugins/RemoteControl/src/RemoteControl.hpp
  plugins/RemoteControl/src/RequestHandler.cpp
  plugins/RemoteControl/src/RequestHandler.hpp
  plugins/RemoteControl/src/ScriptService.hpp
  plugins/RemoteControl/src/SimbadService.cpp
  plugins/RemoteControl/src/SimbadService.hpp
  plugins/RemoteControl/src/StelActionService.hpp
  plugins/RemoteControl/src/StelPropertyService.hpp
  plugins/RemoteControl/src/ViewService.hpp
  plugins/RemoteControl/src/gui/RemoteControlDialog.cpp
  plugins/RemoteControl/src/gui/RemoteControlDialog.hpp
  src/StelMainView.cpp
  src/StelMainView.hpp
  src/scripting/StelMainScriptAPI.cpp
  src/scripting/StelMainScriptAPI.hpp
Labels: feature, importance: medium
