Repository Stellarium/stellarium, pull requests merged in 2023-10, with the labels that each got.

#3438 Make objects split by cylinder projections wraparound appear on one side of the screen
  src/core/StelProjector.hpp
  src/core/StelProjectorClasses.cpp
  src/core/StelProjectorClasses.hpp
  src/core/modules/Planet.cpp
Labels: enhancement, importance: medium

#3447 First build of Stellarium for Windows on ARM on AppVeyor
  .appveyor.yml
  src/CMakeLists.txt
Labels: infrastructure

#3450 Update SpoutLibrary
  .appveyor.yml
  CMakeLists.txt
  src/external/SpoutLibrary.h
  util/spout2/ARM64/SpoutLibrary.dll
  util/spout2/ARM64/SpoutLibrary.lib
  util/spout2/Win32/SpoutLibrary.dll
  util/spout2/Win32/SpoutLibrary.lib
  util/spout2/licence.txt
  util/spout2/x64/SpoutLibrary.dll
  util/spout2/x64/SpoutLibrary.lib
Labels: dependencies

#3452 Publish Windows on Arm build
  .appveyor.yml
  CMakeLists.txt
  src/CMakeLists.txt
  util/qtpaths_workaround.bat
Labels: infrastructure

#3414 Modernize Mesa library
  .appveyor.yml
  guide/ch_advanced_use.tex
  src/CLIProcessor.cpp
  src/core/StelTexture.cpp
  src/core/modules/Landscape.cpp
Labels: importance: medium, infrastructure, qt, mesa

#3483 TUI fixes
  plugins/TextUserInterface/src/TextUserInterface.cpp
  plugins/TextUserInterface/src/TextUserInterface.hpp
  src/core/StelObject.cpp
Labels: enhancement, importance: medium
