Repository Stellarium/stellarium, pull requests merged in 2023-01, with the labels that each got.

#3011 Use generic-icon in mime file
  data/stellarium.xml
Labels: infrastructure

#3009 Allow texture decimation
  guide/app_config_ini.tex
  plugins/NavStars/src/NavStars.hpp
  src/core/StelSkyImageTile.cpp
  src/core/StelSkyImageTile.hpp
  src/core/StelSkyLayerMgr.cpp
  src/core/StelSkyLayerMgr.hpp
  src/core/StelTexture.cpp
  src/core/StelTexture.hpp
  src/core/StelTextureMgr.cpp
Labels: enhancement, importance: medium

#3017 Implement limb darkening for the Sun
  data/shaders/planet.frag
  src/core/modules/Planet.cpp
Labels: enhancement
