Repository Stellarium/stellarium, pull requests merged in 2023-03, with the labels that each got.

#3063 Updated scheme of version numbering
  CMakeLists.txt
  cmake/Info.plist.cmake
  cmake/version.tex.cmake
  guide/ch_introduction.tex
  src/core/StelModuleMgr.cpp
  src/core/StelUtils.cpp
  src/core/StelUtils.hpp
Labels: infrastructure

#3059 Tweak screen intersect callback
  plugins/ArchaeoLines/src/ArchaeoLines.cpp
  src/core/StelPainter.cpp
  src/core/modules/GridLinesMgr.cpp
Labels: enhancement

#3089 Fix building for CI/Linux nodes
  .github/workflows/appimage.yml
  .github/workflows/ci-beta.yml
  .github/workflows/ci.yml
  .github/workflows/code-quality.yml
  .github/workflows/codeql-analysis.yml
Labels: infrastructure

#3093 Added GUI to manually entering FOV
  src/core/StelMovementMgr.hpp
  src/core/StelProjector.hpp
  src/core/StelProjectorClasses.cpp
  src/core/StelSkyLayerMgr.cpp
  src/gui/StelGui.hpp
  src/gui/StelGuiItems.cpp
  src/gui/ViewDialog.cpp
  src/gui/ViewDialog.hpp
  src/gui/viewDialog.ui
Labels: feature
