Repository Stellarium/stellarium, pull requests merged in 2024-09, with the labels that each got.

#2754 Add abort telescope slew signals to LX200 and NexStar telescopes
  plugins/TelescopeControl/src/ASCOM/TelescopeClientASCOM.hpp
  plugins/TelescopeControl/src/Lx200/Lx200Connection.cpp
  plugins/TelescopeControl/src/Lx200/Lx200Connection.hpp
  plugins/TelescopeControl/src/Lx200/TelescopeClientDirectLx200.cpp
  plugins/TelescopeControl/src/Lx200/TelescopeClientDirectLx200.hpp
  plugins/TelescopeControl/src/NexStar/NexStarCommand.cpp
  plugins/TelescopeControl/src/NexStar/NexStarCommand.hpp
  plugins/TelescopeControl/src/NexStar/NexStarConnection.cpp
  plugins/TelescopeControl/src/NexStar/NexStarConnection.hpp
  plugins/TelescopeControl/src/NexStar/TelescopeClientDirectNexStar.cpp
  plugins/TelescopeControl/src/NexStar/TelescopeClientDirectNexStar.hpp
  plugins/TelescopeControl/src/TelescopeClient.cpp
  plugins/TelescopeControl/src/TelescopeClient.hpp
  plugins/TelescopeControl/src/TelescopeControl.hpp
  plugins/TelescopeControl/src/common/Socket.cpp
  plugins/TelescopeControl/src/common/Socket.hpp
  plugins/TelescopeControl/src/gui/SlewDialog.cpp
Labels: enhancement, help wanted, importance: medium

#3887 Disable ASCOM on Qt6
  guide/plg_atTheTelescope.tex
  plugins/TelescopeControl/src/ASCOM/CMakeLists.txt
  plugins/TelescopeControl/src/CMakeLists.txt
  plugins/TelescopeControl/src/TelescopeClient.cpp
  plugins/TelescopeControl/src/common/CMakeLists.txt
  plugins/TelescopeControl/src/common/Socket.cpp
  plugins/TelescopeControl/src/common/Socket.hpp
  plugins/TelescopeControl/src/gui/CMakeLists.txt
  plugins/TelescopeControl/src/gui/TelescopeConfigurationDialog.cpp
  plugins/TelescopeControl/src/gui/TelescopeConfigurationDialog.hpp
Labels: enhancement, importance: medium, qt

#3858 Cast a reddish tint over the landscape when sun is low.
  plugins/Scenery3d/src/S3DRenderer.cpp
  plugins/Scenery3d/src/S3DRenderer.hpp
  src/core/modules/Landscape.cpp
  src/core/modules/Landscape.hpp
  src/core/modules/LandscapeMgr.cpp
  src/core/modules/LandscapeMgr.hpp
  src/core/modules/Planet.cpp
Labels: feature, importance: low

#3878 Orbit color and selection improvements
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/core/modules/SolarSystem.cpp
  src/core/modules/SolarSystem.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/ConfigureOrbitColorsDialog.cpp
  src/gui/ViewDialog.cpp
  src/gui/orbitColorsDialog.ui
  src/gui/viewDialog.ui
Labels: enhancement, importance: high

#3792 Simplify gridline intersect callbacks
  src/core/modules/GridLinesMgr.cpp
Labels: bug, enhancement, importance: medium

#3880 Added ability to use a wider range of dates for AstroCalc/Ephemeris tool
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: enhancement
