Repository Stellarium/stellarium, pull requests merged in 2024-07, with the labels that each got.

#3780 Fix custom user dir option.
  src/core/StelFileMgr.cpp
Labels: bug, importance: low

#3775 Allow disabling StelAudioMgr at runtime
  guide/app_config_ini.tex
  guide/ch_advanced_use.tex
  src/CLIProcessor.cpp
  src/core/StelApp.cpp
  src/core/StelAudioMgr.cpp
  src/core/StelAudioMgr.hpp
  src/core/StelVideoMgr.cpp
  src/core/StelVideoMgr.hpp
Labels: enhancement, importance: medium

#3802 Bundled QtCompress
  CMakeLists.txt
  plugins/Satellites/src/Satellites.cpp
  src/CMakeLists.txt
  src/core/modules/LandscapeMgr.cpp
  src/external/CMakeLists.txt
  src/external/qtcompress/qzip.cpp
  src/external/qtcompress/qzipreader.h
  src/external/qtcompress/qzipwriter.h
Labels: infrastructure, dependencies
