Repository Stellarium/stellarium, pull requests merged in 2025-01, with the labels that each got.

#4046 Add Sh2-245 as Eridanus Loop
  nebulae/default/names.dat
Labels: data

#4048 Add common names to NGC2467, LDN988, Sh2-245
  nebulae/default/names.dat
Labels: data

#4049 Apply font size settings to Oculars plugin
  plugins/Oculars/src/Oculars.cpp
  plugins/Oculars/src/Oculars.hpp
  plugins/Oculars/src/gui/OcularsGuiPanel.cpp
  plugins/Oculars/src/gui/OcularsGuiPanel.hpp
  src/gui/StelGuiItems.hpp
Labels: subsystem: gui

#4050 Fix typos in modern_iau sky culture
  skycultures/modern_iau/description.en.utf8
Labels: description, subsystem: skycultures, purpose: cultural astronomy

#4054 AstroCalc: Add a filter by eclipse type
  data/gui/normalStyle.css
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcDialog.ui
Labels: enhancement, subsystem: astrocalc

#4023 Add parallax effect to stars
  guide/ch_astronomical_concepts.tex
  plugins/Exoplanets/src/Exoplanet.cpp
  plugins/Novae/src/Nova.cpp
  plugins/Pulsars/src/Pulsar.cpp
  plugins/Quasars/src/Quasar.cpp
  plugins/Supernovae/src/Supernova.cpp
  src/core/StelCore.cpp
  src/core/StelCore.hpp
  src/core/StelSkyImageTile.cpp
  src/core/StelToast.cpp
  src/core/modules/AsterismMgr.cpp
  src/core/modules/ConstellationMgr.cpp
  src/core/modules/CustomObject.cpp
  src/core/modules/MarkerMgr.cpp
  src/core/modules/Nebula.cpp
  src/core/modules/NomenclatureMgr.cpp
  src/core/modules/Planet.cpp
  src/core/modules/Planet.hpp
  src/core/modules/SolarSystem.cpp
  src/core/modules/Star.hpp
  src/core/modules/StarMgr.cpp
  src/core/modules/StarWrapper.hpp
  src/core/modules/ZoneArray.cpp
  src/core/modules/ZoneArray.hpp
  src/core/planetsephems/EphemWrapper.cpp
  src/core/planetsephems/EphemWrapper.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/configurationDialog.ui
Labels: purpose: didactic, subsystem: catalogs

#4096 Added missing Bayer/Flamsteed designations for stars
  stars/hip_gaia3/name.fab
Labels: data, subsystem: catalogs

#4092 Make all splash screen text scalable
  data/splash-gray.png
  data/splash.png
  src/StelSplashScreen.cpp
  src/StelSplashScreen.hpp
Labels: subsystem: gui

#4103 Make it possible to scale screen buttons independently
  plugins/Oculars/src/Oculars.cpp
  src/core/StelApp.cpp
  src/core/StelApp.hpp
  src/gui/ConfigurationDialog.cpp
  src/gui/StelGuiItems.cpp
  src/gui/StelGuiItems.hpp
  src/gui/configurationDialog.ui
Labels: subsystem: gui

#4108 Fix wrong Gaia ID for HIP 101769 and HIP 25606 in the star catalog
  src/core/modules/StarMgr.cpp
  stars/hip_gaia3/defaultStarsConfig.json
  stars/hip_gaia3/stars_0_0v0_14.cat
  stars/hip_gaia3/stars_0_0v0_15.cat
Labels: subsystem: catalogs
