Repository Stellarium/stellarium, pull requests merged in 2025-03, with the labels that each got.

#4175 AstroCalc/Almanac
  data/gui/normalStyle.css
  po/stellarium/POTFILES.in
  src/CMakeLists.txt
  src/gui/AstroCalcAlmanacWidget.cpp
  src/gui/AstroCalcAlmanacWidget.hpp
  src/gui/AstroCalcDialog.cpp
  src/gui/AstroCalcDialog.hpp
  src/gui/astroCalcAlmanacWidget.ui
  src/gui/astroCalcDialog.ui
Labels: subsystem: astrocalc

#4184 Compute position angle and separation of binary stars system
  src/core/modules/Star.hpp
  src/core/modules/StarWrapper.cpp
Labels: subsystem: catalogs

#4195 Improvement fix for issue #4178
  src/core/modules/StarMgr.cpp
  src/core/modules/StarMgr.hpp
Labels: subsystem: skycultures

#4203 Don't load any high level star catalog if a lower level star catalog is missing
  doc/fileStructure.doxygen
  guide/app_star_catalogue.tex
  src/core/modules/StarMgr.cpp
  src/core/modules/StarMgr.hpp
  src/gui/ConfigurationDialog.cpp
Labels: subsystem: catalogs

#4226 Fix accents in a JSON snippet
  guide/ch_skycultures.tex
  guide/structure.tex
Labels: documentation

#4231 Add padding to bounding cap to avoid clipping on small FOV
  src/core/StelProjector.cpp
  src/core/modules/StarMgr.cpp
Labels: importance: low

#4237 Add pronounce and IPA tags in Siberian SC
  skycultures/russian_siberian/index.json
Labels: data, subsystem: skycultures

#4190 SUG: Foreword for 25.1
  guide/ch_foreword.tex
  guide/ch_introduction.tex
Labels: documentation

#4234 two Chinese Sky Cultures
  skycultures/CMakeLists.txt
  skycultures/chinese_chenzhuo/CMakeLists.txt
  skycultures/chinese_chenzhuo/description.md
  skycultures/chinese_chenzhuo/index.json
  skycultures/chinese_chenzhuo/po/zh_CN.po
  skycultures/chinese_chenzhuo/po/zh_HK.po
  skycultures/chinese_chenzhuo/po/zh_TW.po
  skycultures/chinese_medieval/index.json
Labels: data, subsystem: skycultures
