Repository Stellarium/stellarium, pull requests merged in 2025-04, with the labels that each got.

#4264 Add a few more telescopes to Camera Mosaic Plugins
  guide/plg_atTheTelescope.tex
  plugins/MosaicCamera/README
  plugins/MosaicCamera/resources/DECam.json
  plugins/MosaicCamera/resources/Euclid.json
  plugins/MosaicCamera/resources/HSC.json
  plugins/MosaicCamera/resources/HST.json
  plugins/MosaicCamera/resources/JWST.json
  plugins/MosaicCamera/resources/LATISS.json
  plugins/MosaicCamera/resources/LSSTCam.json
  plugins/MosaicCamera/resources/MegaPrime.json
  plugins/MosaicCamera/resources/MosaicCamera.qrc
  plugins/MosaicCamera/resources/Roman.json
  plugins/MosaicCamera/resources/camera_order.json
  plugins/MosaicCamera/src/MosaicCamera.cpp
  plugins/MosaicCamera/src/MosaicCamera.hpp
  plugins/MosaicCamera/src/gui/MosaicCameraDialog.cpp
  plugins/MosaicCamera/src/gui/MosaicCameraDialog.hpp
  plugins/MosaicCamera/src/gui/mosaicCameraDialog.ui
  plugins/MosaicCamera/src/translations.fab
  plugins/MosaicCamera/utils/parse_json.sh
  po/stellarium/POTFILES.in
Labels: subsystem: plugins

#4289 Add Manual Dependency Download Instructions to README
  BUILDING.md
Labels: documentation, dependencies

#4298 Updated settings for AppVeyor
  .appveyor.yml
  CMakeLists.txt
  cmake/modules/FindISCC.cmake
  cmake/stellarium-patch.iss6.cmake
  cmake/stellarium.iss.cmake
  cmake/stellarium.iss6.cmake
Labels: infrastructure, os: windows
